// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EpaK
double EpaK(double x);
RcppExport SEXP _nftsport_EpaK(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(EpaK(x));
    return rcpp_result_gen;
END_RCPP
}
// locLinSmootherC
arma::cube locLinSmootherC(double bw, arma::vec x, arma::cube y, bool db_kernel);
RcppExport SEXP _nftsport_locLinSmootherC(SEXP bwSEXP, SEXP xSEXP, SEXP ySEXP, SEXP db_kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type db_kernel(db_kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(locLinSmootherC(bw, x, y, db_kernel));
    return rcpp_result_gen;
END_RCPP
}
// ftsQ
double ftsQ(double tau, int trim, arma::vec t, arma::cube e, int sn);
RcppExport SEXP _nftsport_ftsQ(SEXP tauSEXP, SEXP trimSEXP, SEXP tSEXP, SEXP eSEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    rcpp_result_gen = Rcpp::wrap(ftsQ(tau, trim, t, e, sn));
    return rcpp_result_gen;
END_RCPP
}
// Qmultiplier
arma::mat Qmultiplier(double tau, int trim, arma::vec t, arma::cube e, int sn);
RcppExport SEXP _nftsport_Qmultiplier(SEXP tauSEXP, SEXP trimSEXP, SEXP tSEXP, SEXP eSEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    rcpp_result_gen = Rcpp::wrap(Qmultiplier(tau, trim, t, e, sn));
    return rcpp_result_gen;
END_RCPP
}
// Qdist
arma::mat Qdist(arma::mat V, int n, double tau, int N, int B, int sn, int L);
RcppExport SEXP _nftsport_Qdist(SEXP VSEXP, SEXP nSEXP, SEXP tauSEXP, SEXP NSEXP, SEXP BSEXP, SEXP snSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(Qdist(V, n, tau, N, B, sn, L));
    return rcpp_result_gen;
END_RCPP
}
// Qmultiplierj_uni
arma::mat Qmultiplierj_uni(double tau, int q, int trim, arma::vec t, arma::cube e, arma::cube dotmat, int sn);
RcppExport SEXP _nftsport_Qmultiplierj_uni(SEXP tauSEXP, SEXP qSEXP, SEXP trimSEXP, SEXP tSEXP, SEXP eSEXP, SEXP dotmatSEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type e(eSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type dotmat(dotmatSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    rcpp_result_gen = Rcpp::wrap(Qmultiplierj_uni(tau, q, trim, t, e, dotmat, sn));
    return rcpp_result_gen;
END_RCPP
}
// compute_dotmat
arma::cube compute_dotmat(arma::cube e, int sn);
RcppExport SEXP _nftsport_compute_dotmat(SEXP eSEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_dotmat(e, sn));
    return rcpp_result_gen;
END_RCPP
}
// ftsQcross_universal
double ftsQcross_universal(double tau, int trim, arma::vec t, arma::cube e, arma::cube dotmat, int sn);
RcppExport SEXP _nftsport_ftsQcross_universal(SEXP tauSEXP, SEXP trimSEXP, SEXP tSEXP, SEXP eSEXP, SEXP dotmatSEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type e(eSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type dotmat(dotmatSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    rcpp_result_gen = Rcpp::wrap(ftsQcross_universal(tau, trim, t, e, dotmat, sn));
    return rcpp_result_gen;
END_RCPP
}
// Qdist_uni
arma::mat Qdist_uni(arma::cube res, arma::cube dotmat, arma::vec t, int trim, int n, double tau, int N, int B, int sn, int L);
RcppExport SEXP _nftsport_Qdist_uni(SEXP resSEXP, SEXP dotmatSEXP, SEXP tSEXP, SEXP trimSEXP, SEXP nSEXP, SEXP tauSEXP, SEXP NSEXP, SEXP BSEXP, SEXP snSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type res(resSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type dotmat(dotmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(Qdist_uni(res, dotmat, t, trim, n, tau, N, B, sn, L));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nftsport_EpaK", (DL_FUNC) &_nftsport_EpaK, 1},
    {"_nftsport_locLinSmootherC", (DL_FUNC) &_nftsport_locLinSmootherC, 4},
    {"_nftsport_ftsQ", (DL_FUNC) &_nftsport_ftsQ, 5},
    {"_nftsport_Qmultiplier", (DL_FUNC) &_nftsport_Qmultiplier, 5},
    {"_nftsport_Qdist", (DL_FUNC) &_nftsport_Qdist, 7},
    {"_nftsport_Qmultiplierj_uni", (DL_FUNC) &_nftsport_Qmultiplierj_uni, 7},
    {"_nftsport_compute_dotmat", (DL_FUNC) &_nftsport_compute_dotmat, 2},
    {"_nftsport_ftsQcross_universal", (DL_FUNC) &_nftsport_ftsQcross_universal, 6},
    {"_nftsport_Qdist_uni", (DL_FUNC) &_nftsport_Qdist_uni, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_nftsport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
