# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EpaK <- function(x) {
    .Call(`_nftsport_EpaK`, x)
}

locLinSmootherC <- function(bw, x, y, db_kernel = 0L) {
    .Call(`_nftsport_locLinSmootherC`, bw, x, y, db_kernel)
}

ftsQ <- function(tau, trim, t, e, sn) {
    .Call(`_nftsport_ftsQ`, tau, trim, t, e, sn)
}

Qmultiplier <- function(tau, trim, t, e, sn) {
    .Call(`_nftsport_Qmultiplier`, tau, trim, t, e, sn)
}

Qdist <- function(V, n, tau, N, B, sn, L = 5L) {
    .Call(`_nftsport_Qdist`, V, n, tau, N, B, sn, L)
}

Qmultiplierj_uni <- function(tau, q, trim, t, e, dotmat, sn) {
    .Call(`_nftsport_Qmultiplierj_uni`, tau, q, trim, t, e, dotmat, sn)
}

compute_dotmat <- function(e, sn) {
    .Call(`_nftsport_compute_dotmat`, e, sn)
}

ftsQcross_universal <- function(tau, trim, t, e, dotmat, sn) {
    .Call(`_nftsport_ftsQcross_universal`, tau, trim, t, e, dotmat, sn)
}

Qdist_uni <- function(res, dotmat, t, trim, n, tau, N, B, sn, L = 5L) {
    .Call(`_nftsport_Qdist_uni`, res, dotmat, t, trim, n, tau, N, B, sn, L)
}

